title: Manual de Phacobook
description:  Documentation for Phacobook 

# Build settings
theme: minima

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - features.md
# - errors.md
